### ISSUE TITLE
Add redux-thunk

### ISSUE THREAD

**Issue by trevorgerhardt** [conveyal/woonerf#49]
We currently use [redux-thunk](https://github.com/gaearon/redux-thunk) in the DataTools UI and OTP-RR vs woonerf's redux-[promise](https://github.com/conveyal/woonerf/blob/dev/src/store/promise.js)/[multi](https://github.com/conveyal/woonerf/blob/dev/src/store/multi.js) implementations in Analysis, Commute, and Taui. This may seem like a bikeshedding/style issue on first glance but over the course of time could pretty drastically change how we model our redux actions and reducers. 

Ideally, we'd converge on a style so that the placement of services and logic becomes implicit knowledge and common across our applications. This would also allow for abstracting out common modules and boilerplate that could be placed into woonerf (for example: [fetch](https://github.com/conveyal/woonerf/blob/dev/src/fetch.js)).

My current thoughts are mainly that restrictions can be a positive design constraint over the long term. The power/freedom that redux-thunk provides is useful in a variety of situations but can almost always be replicated with enough thought and work using promise/multi. The restrictions on flow that are required when you cannot `dispatch` anywhere you want may create more sustainable code over the long term.

Let me know your thoughts!

**Comment by trevorgerhardt** [comment]
Also, to allow usage of woonerf/store in DataTools we could temporarily add `redux-thunk` to the middleware stack.

**Comment by landonreed** [comment]
@trevorgerhardt, I think converging on a similar style for actions is preferable in the long run.

For now, is it more of a priority to get datatools on woonerf middleware immediately (in which case we would need to add `redux-thunk`) or to substitute `redux-thunk` out of datatools over time eventually bringing it in line with the "woonerf way".  I think I would opt for the former, just so that datatools doesn't drift farther from the pack.

**Comment by trevorgerhardt** [comment]
@landonreed I agree, we should add it now so that we can use woonerf across all projects.
